language: php

dist: trusty
sudo: false

php:
    - 7.0
#    - 7.1
#    - 7.2
#    - nightly

matrix:
    fast_finish: true
#    allow_failures:
#        - php: nightly

git:
    depth: 1

env:
    global:
        - PATH="$PATH:~/bin"
        - TEST_USER=testuser
        - TEST_PASSWORD=applesauce
        - TESTING_SERVER_HOST=127.0.0.1
        - TESTING_SERVER_PORT=143

cache:
    apt: true
    ccache: true
    timeout: 604800
    directories:
        - vendor
        - $HOME/.composer/cache
        - $HOME/pear

before_install:
    - if [ ! -z "${GH_TOKEN}" ]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;

install:
    - docker pull pdffiller/dovecot2.3-testing-alpine37
    - |
        composer install \
            --prefer-dist \
            --no-ansi \
            --optimize-autoloader \
            --dev

before_script:
    - docker run -d -p 143:143 pdffiller/dovecot2.3-testing-alpine37

script:
    - vendor/bin/phpunit --disallow-test-output

after_success:
    - if [[ ! -z "${CODECOV_TOKEN}" ]]; then bash <(curl -s https://codecov.io/bash); fi;

notifications:
    email:
        on_success: never
        on_failure: never
