language: php

php:
    - 5.6
#    - 7.0
#    - 7.1
#    - 7.2

matrix:
    fast_finish: true

before_script:
    - composer self-update
    - composer install

script:
#    - ./vendor/bin/phpunit --verbose
