language: php

dist: trusty
sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

git:
    depth: 1

cache:
    apt: true
    ccache: true
    timeout: 604800
    directories:
        - vendor
        - $HOME/.composer/cache
        - $HOME/pear

before_install:
    - if [ ! -z "${GH_TOKEN}" ]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;

install:
    - docker pull pdffiller/dovecot
    - |
        composer install \
            --prefer-dist \
            --no-ansi \
            --optimize-autoloader \
            --dev

before_script:
    - |
        docker run -d \
            -p 143:143 \
            -p 993:993 \
            -v $(pwd)/tests/ci/dovecot-users:/opt/dovecot/etc/dovecot/users:ro \
            -v $(pwd)/tests/ci/dovecot-local.conf:/opt/dovecot/etc/dovecot/local.conf:ro \
            -v $(pwd)/tests/ci/00-provision.sh:/entrypoint.d/00-provision.sh:ro \
            -v $(pwd)/tests/data/Maildir.tar:/data/Maildir.tar:ro \
            -v $(pwd)/tests/data/Attachments.tar:/data/Attachments.tar:ro \
            pdffiller/dovecot

script:
    - vendor/bin/phpunit --disallow-test-output

after_success:
    - if [[ ! -z "${CODECOV_TOKEN}" ]]; then bash <(curl -s https://codecov.io/bash); fi;

notifications:
    email:
        on_success: never
        on_failure: never
